version: '3'

services:
  mopidy:
    container_name: mopidy
    build:
      context: ./mopidy
    command: mopidy
    ports:
      - "6600:6600"
      - "6680:6680"
    volumes:
      - ./mopidy-data:/var/lib/mopidy:delegated
    environment:
      - MOPIDY_USERNAME=${MOPIDY_USERNAME}
      - MOPIDY_PASSWORD=${MOPIDY_PASSWORD}
      - MOPIDY_CLIENT_ID=${MOPIDY_CLIENT_ID}
      - MOPIDY_CLIENT_SECRET=${MOPIDY_CLIENT_SECRET}
