version: '3.4'
services:
  jukebox-client:
    container_name: jukebox-client
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
  jukebox-api:
    container_name: jukebox-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - './backend:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '8080:8080'
