version: '3.7'

services:
  mongodb:
    image: mongo:4.2-bionic
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=jb-dev
    volumes:
      - ./mongodb-data/db:/data/db
    ports:
      - 27017:27017
