version: '3.4'
services:
  jukebox-client:
    container_name: jukebox-client
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
      - PORT=3001
      - REACT_APP_WS_URL=localhost
      - REACT_APP_WS_PORT=8080
  jukebox-api:
    container_name: jukebox-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - './backend:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development
      - PORT=8080
      - IS_ALIVE_TIMEOUT=30000
      - WS_MOPIDY_URL=jukebox.local
      - WS_MOPIDY_PORT=6680

