version: '3.4'
services:
  jukebox-client:
    container_name: jukebox-client
    build:
      context: ./frontend
      args:
        - NODE_ENV=development
    command: npm start
    volumes:
      - ./frontend:/opt/app:delegated
      - /opt/app/node_modules
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
      - PORT=3001
      - REACT_APP_WS_URL=localhost
      - REACT_APP_WS_PORT=8080
  jukebox-api:
    container_name: jukebox-api
    build:
      context: ./backend
      args:
        - NODE_ENV=development
    volumes:
      - ./backend:/opt/app:delegated
      - /opt/app/node_modules
    command: npm start
    ports:
      - "8080:8080"
      - "5858:5858"
      - "9229:9229"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - PORT=8080
      - IS_ALIVE_TIMEOUT=30000
      - WS_MOPIDY_URL=mopidy-prod.local
      - WS_MOPIDY_PORT=6680
      - MONGODB_URL=mongodb://mongodb:27017/jb-dev
      - JWT_SECRET=secretshh
      - SPOTIFY_ID=${SPOTIFY_ID}
      - SPOTIFY_SECRET=${SPOTIFY_SECRET}
      - SPOTIFY_NEW_TRACKS_ADDED_LIMIT=3
      - LOCAL_STORAGE_PATH=./local-cache
  mongodb:
    image: mongo:3.6.4
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
  mongodb-seed:
    build: ./db-seed
    links:
      - mongodb
