name: jukebox-build-and-test

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build and test frontend
      run: |
        cd frontend
        npm install
        npm run build --if-present
        npm test -- --coverage
      env:
        CI: true
    - name: Build and test backend
      run: |
        cd backend
        npm install
        npm run build --if-present
        npm test -- --coverage
      env:
        CI: true
        CLIENT_ID: abcdefg
        CLIENT_ID_PRODUCTION: abcdefg
        LOCAL_STORAGE_PATH: /tmp/jukebox
        MONGODB_URL: mongodb://mongodb:27017/jb-dev
        NOW_PLAYING_URL: 'https://nowplaying.dev'
        SPOTIFY_ID: 0123456789abcdef0123456789abcdef
        SPOTIFY_NEW_TRACKS_ADDED_LIMIT: 3
        SPOTIFY_SECRET: 0123456789abcdef0123456789abcdef
        WS_MOPIDY_PORT: 6680
        WS_MOPIDY_URL: mopidy-prod.local
